CD設定

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,52 +1,73 @@
-# Golang CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-go/ for more details
-version: 2
-jobs:
-  build:
-    docker:
-      # specify the version
-      - image: circleci/golang:1.15.2
+version: 2.1
 
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      - image: circleci/mysql:8.0.21
-        environment:
-          MYSQL_ROOT_PASSWORD: power-phrase2
-          MYSQL_DATABASE: power-phrase2-test
-          MYSQL_USER: kazuya
-          MYSQL_PASSWORD: kazuya
+orbs:
+    # circleci/aws-ecr@6.1.0というorbをaws-ecrというaliasをつけて扱う
+    aws-ecr: circleci/aws-ecr@6.1.0
+    aws-ecs: circleci/aws-ecs@0.0.8
 
-    #### TEMPLATE_NOTE: go expects specific checkout path representing url
-    #### expecting it in the form of
-    ####   /go/src/github.com/circleci/go-tool
-    ####   /go/src/bitbucket.org/circleci/go-tool
-    working_directory: /go/src/github.com/k-kazuya0926/power-phrase2-api
-    steps:
-      - checkout
+workflows:
+    # build_and_push_imageという名前のworkflowを定義
+    build_and_push_image:
+        # workflowで実行するjobの順番を定義
+        jobs:
+        - aws-ecr/build-and-push-image:
+            region: AWS_REGION
+            account-url: AWS_ECR_ACCOUNT_URL
+            repo: 'power-phrase2-api'
+            tag: "${CIRCLE_SHA1}"
+        - aws-ecs/deploy-service-update:
+            requires:
+                - aws-ecr/build-and-push-image
+            family: 'power-phrase2-api-task'
+            cluster-name: ' power-phrase2-api-cluster'
+            service-name: 'power-phrase2-api-service'
+            container-image-name-updates: 'container=power-phrase2-api-container,tag=${CIRCLE_SHA1}'
 
-      # specify any bash command here prefixed with `run: `
-      - run:
-      # プライマリ コンテナは MySQL ではないため、準備が完了するまで sleep コマンドを実行します。
-          name: MySQL が準備できるまで待機
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+# jobs:
+#   build:
+#     docker:
+#       # specify the version
+#       - image: circleci/golang:1.15.2
 
-      - run: mv src/* .
-      - restore_cache:
-          key: mod-{{ checksum "go.sum" }}
+#       # Specify service dependencies here if necessary
+#       # CircleCI maintains a library of pre-built images
+#       # documented at https://circleci.com/docs/2.0/circleci-images/
+#       - image: circleci/mysql:8.0.21
+#         environment:
+#           MYSQL_ROOT_PASSWORD: power-phrase2
+#           MYSQL_DATABASE: power-phrase2-test
+#           MYSQL_USER: kazuya
+#           MYSQL_PASSWORD: kazuya
 
-      - run: go get -v -t -d ./...
-      - run: go test -v ./...
+#     #### TEMPLATE_NOTE: go expects specific checkout path representing url
+#     #### expecting it in the form of
+#     ####   /go/src/github.com/circleci/go-tool
+#     ####   /go/src/bitbucket.org/circleci/go-tool
+#     working_directory: /go/src/github.com/k-kazuya0926/power-phrase2-api
+#     steps:
+#       - checkout
 
-      - save_cache:
-                key: mod-{{ checksum "go.sum" }}
-                paths:
-                  - $GOPATH/pkg/mod
+#       # specify any bash command here prefixed with `run: `
+#       - run:
+#       # プライマリ コンテナは MySQL ではないため、準備が完了するまで sleep コマンドを実行します。
+#           name: MySQL が準備できるまで待機
+#           command: |
+#             for i in `seq 1 10`;
+#             do
+#               nc -z 127.0.0.1 3306 && echo Success && exit 0
+#               echo -n .
+#               sleep 1
+#             done
+#             echo Failed waiting for MySQL && exit 1
+
+#       - run: mv src/* .
+#       - restore_cache:
+#           key: mod-{{ checksum "go.sum" }}
+
+#       - run: go get -v -t -d ./...
+#       - run: go test -v ./...
+
+#       - save_cache:
+#                 key: mod-{{ checksum "go.sum" }}
+#                 paths:
+#                   - $GOPATH/pkg/mod
